### ISSUE TITLE
Crash on lollipop

### ISSUE THREAD

**Issue by gokulkrizh** [googlecodelabs/android-paging#1]
JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xf0

removed emoji on no_results string resolves crashes but  i wanna know why is this crashing..

**Comment by LittleMango** [comment]
I met the same situation and the same exception information.

**Comment by PritishSawant** [comment]
Remove the smiley from strings.xml

**Comment by kaushiknsanji** [comment]
Replace the smiley with `&#x1F613;`

```
<resources>
    <string name="app_name">Paging</string>
    <string name="loading">Loading</string>
    <string name="language">Language: %s</string>
    <string name="search_hint">GitHub Repository</string>
    <string name="no_results">No results &#x1F613;</string>
    <string name="unknown">\?</string>
</resources>
```
