### ISSUE TITLE
Final code for section 9 does not match the description

### ISSUE THREAD

**Issue by Len512** [googlecodelabs/android-paging#101]
<b>Section 9: Trigger network updates</b>

In the final code for SearchRepositoriesActivity `private fun initSearch(query: String)` is different than the one explained in the tutorial some lines above.
```kotlin
lifecycleScope.launch {
            @OptIn(ExperimentalPagingApi::class)
            adapter.dataRefreshFlow.collect {
                binding.list.scrollToPosition(0)
            }
        }
```

instead of

```kotlin
lifecycleScope.launch {
            adapter.loadStateFlow
                   // Only emit when REFRESH LoadState changes.
                   .distinctUntilChangedBy { it.refresh }
                   // Only react to cases where REFRESH completes i.e., NotLoading.
                   .filter { it.refresh is LoadState.NotLoading }
                   .collect { binding.list.scrollToPosition(0) }
        }
```

Also in the final code for the SearchRepositoriesActivity, there is a method included that is not used anymore i.e. `private fun showEmptyList(show: Boolean)`

**Comment by florina-muntenescu** [comment]
Thank you for reporting this! 
`showEmptyList` is only removed a bit later so keeping it there for now.
