### ISSUE TITLE
How to implement ItemKeyedDataSource of Paging 2 with the new Paging library 3 with RxSupport like RxPagingSource

### ISSUE THREAD

**Issue by Aminul-Haque-Aome** [googlecodelabs/android-paging#102]
In fact, I am trying to migrate from paging 2 to paging 3. Already I have successfully implemented PageKeyedDataSource of Paging 2 with RxpagingSource in my codebase. But when I tried to implement  ItemKeyedDataSource of Paging 2 to Paging library 3, I got confused to implement that. Please include this ItemKeyedDataSource support in this codebase, so that we can easily implement this. Thanks all

**Comment by florina-muntenescu** [comment]
Checkout the [PagingWithNetwork](https://github.com/android/architecture-components-samples/tree/master/PagingWithNetworkSample) sample. It should give you some indications on how to implement the `ItemKeyedDataSource`

**Comment by Aminul-Haque-Aome** [comment]
Thanks a lot for your response dear ❤️ ❤️
