### ISSUE TITLE
Differences in Step #9

### ISSUE THREAD

**Issue by jorgecasariego** [googlecodelabs/android-paging#103]
Hi, I want to add something related to the step 9. In the description says to update **initSearch** method and at every new emission of the flow, let's scroll to position 0 adding this code:

![image](https://user-images.githubusercontent.com/2581647/91896142-5da2ef80-ec66-11ea-9324-91b16193fb3b.png)

But at the end, in the Activity with the complete code shows this:

![image](https://user-images.githubusercontent.com/2581647/91896252-862ae980-ec66-11ea-986f-f200288af56f.png)

**Comment by florina-muntenescu** [comment]
Thank you for reporting this! Fixed
