### ISSUE TITLE
Step 12 - Description issue

### ISSUE THREAD

**Issue by jorgecasariego** [googlecodelabs/android-paging#104]
In the paragraph on **Insert Separators** it says : _the first operation we need to add is to transform each Repo into a **UiModel.Repo**_

If I’m not wrong the text should say: the first operation we need to add is to transform each Repo into a **UiModel.RepoItem**

The same thing in the text: _To do this, we can use the Flow.map operator and then map each PagingData to build a new **UiModel.Repo** from the current Repo item_

**Comment by florina-muntenescu** [comment]
Thank you for reporting this! Fixed
