### ISSUE TITLE
Same value was passed as the nextKey in two sequential Pages loaded from a PagingSource in Paging Library 3 Android

### ISSUE THREAD

**Issue by Aminul-Haque-Aome** [googlecodelabs/android-paging#107]
I migrated from paging 2 to paging 3. I tried to implement ItemKeyedDataSource of Paging 2 to Paging library 3. But the problem I was facing is, the same value(currentJodId) was passed as the nextkey in two sequential Pages loaded. And After that app crashes. but if I add "keyReuseSupported = true" in DataSource, app does not crash. But it started calling same item id as the nextkey.

check this please
https://stackoverflow.com/questions/63870064/same-value-was-passed-as-the-nextkey-in-two-sequential-pages-loaded-from-a-pagin

**Comment by florina-muntenescu** [comment]
This is not an issue related to the codelab. Please use the [official issue tracker](https://issuetracker.google.com/issues/new?component=413106&template=1096385) for this.
cc @dlam
