### ISSUE TITLE
Does PagingData Run on a Background Thread by Default in Paging 3 Library?

### ISSUE THREAD

**Issue by AdamSHurwitz** [googlecodelabs/android-paging#109]
**Is background threading managed automatically with `PagingData` as it is with `PagedList`, and then returned on the main thread?**

From the logs below, it appears `PagingData` is not run on the backgroud thread in the Paging 3 library compared to `PagedList` in Paging 2. I've created logs within the Codelab sample inside the _GithubPagingSource_ and _SearchRepositoriesActivity_ classes, and re-created in my sample code below.

**Expect**

- _GithubPagingSource_ `override suspend fun load(...)` to run on an IO thread.
- _SearchRepositoriesActivity_ `viewModel.searchRepo(query).collectLatest { ... }` to run on the main thread.

**Observe**

- Both _GithubPagingSource_ `override suspend fun load(...)` and _SearchRepositoriesActivity_ `viewModel.searchRepo(query).collectLatest { ... }` run on the main thread.

# Paging 2

Threading is handled on the background by `PagedList` with `toLiveData` according to the [documentation][paging2].  

> If you use LivePagedListBuilder to get a LiveData<PagedList>, it will initialize PagedLists on a background thread for you.

# Paging 3

The Paging 3 [documentation][paging3] does not mention how threading is managed. However, from the logs, `PagingSource` appears to be running the network request on the main thread and returning the `PagingData` on the main thread.

## Sample 

I've recreated the Codelab pattern in my own sample code below.

_FeedPagingSource.kt_
```Kotlin
class FeedPagingSource : PagingSource<Int, Tweet>() {

    override suspend fun load(params: LoadParams<Int>): LoadResult<Int, Tweet> {
        try {
            val page = params.key ?: 1
            val nextPage = page + 1
            val tweets = Injection.feedService.getTweets(...)
            println("Thread: FeedPagingSource ${Thread.currentThread().name}")
            Log.v(LOG_TAG, "load success: ${tweets}")
            return LoadResult.Page(...)
        } catch (error: Exception) {
            ...
        }
    }
}
```

_FeedRepository.kt_
```Kotlin
class FeedRepository {
    fun initFeed() = Pager(
        config = PagingConfig(pageSize = FEED_PAGEDLIST_SIZE),
        pagingSourceFactory = { FeedPagingSource() }
    ).flow
}
```

_FeedViewModel.kt_
```Kotlin
repository.initFeed().onEach {
    println("Thread: FeedViewModel ${Thread.currentThread().name}")
    _feed.value = it
}.launchIn(viewModelScope)
```

## Attempted Solution

In order to run the `PagingSource` on a background thread, the flow is initiated on `Dispatchers.IO`. However, the log still shows `PagingSource` runs on the main thread in _FeedPagingSource.kt_.

_FeedViewModel.kt_
```Kotlin
repository.initFeed().onEach {
            println("Thread: FeedViewModel ${Thread.currentThread().name}")
            _feed.value = it
}.flowOn(Dispatchers.IO).launchIn(viewModelScope)
```

[paging2]: https://developer.android.com/reference/androidx/paging/PagedList#loading-data
[paging3]: https://developer.android.com/reference/kotlin/androidx/paging/PagingData

**Comment by AdamSHurwitz** [comment]
# Kotlin Coroutines

When implementing `PagingData` and `PagingSource` with Kotlin Coroutines and making a Retrofit network request, as in the sample code above, Retrofit handles the background threading by default and returns on the main thread.

_See: [Does Retrofit make network calls on main thread?](https://stackoverflow.com/a/63986072/2253682) - StackOverflow_

# RxJava

When using RxJava with Retrofit as the network source, the threading needs to be explicitly specified as shown in the Android documentation sample.

_See Android documentation: [Page from network and database][Page from network and database] > [Implement a RemoteMediator][Implement a RemoteMediator]_

[Page from network and database]: https://developer.android.com/topic/libraries/architecture/paging/v3-network-db
[Implement a RemoteMediator]: https://developer.android.com/topic/libraries/architecture/paging/v3-network-db#implement-remotemediator

**Comment by droidevs** [comment]
> # Kotlin Coroutines
> When implementing `PagingData` and `PagingSource` with Kotlin Coroutines and making a Retrofit network request, as in the sample code above, Retrofit handles the background threading by default and returns on the main thread.
> 
> _See StackOverflow: [Does Retrofit make network calls on main thread?](https://stackoverflow.com/a/63986072/2253682)_
> 
> # RxJava
> When using RxJava with Retrofit as the network source, the threading needs to be explicitly specified as shown in the Android documentation sample.
> 
> _See Android documentation: [Page from network and database](https://developer.android.com/topic/libraries/architecture/paging/v3-network-db) > [Implement a RemoteMediator](https://developer.android.com/topic/libraries/architecture/paging/v3-network-db#implement-remotemediator)_

i use local database in paging source [ROOM] can i have a solution to run the room calls in the background
