### ISSUE TITLE
Missing empty view when there are no results

### ISSUE THREAD

**Issue by saulmm** [googlecodelabs/android-paging#110]
On the master branch, there is an empty view aimed to be shown when there are no results. Moreover, the `PagingDataAdapter` class has an `addDataRefreshListener` which notifies if the list is empty or not.

**Comment by saulmm** [comment]
As in alpha-06, `addDataRefreshListener` is deprecated. Use `loadStateListener` + `itemCount` as the deprecation annotation suggests

**Comment by hrgdeveloper** [comment]
could not find itemcount . can you please provide an example . tanx

**Comment by fauzynurn** [comment]
> could not find itemcount . can you please provide an example . tanx

You can use loadStateListener + itemCount from adapter like this : 

`yourAdapter.addLoadStateListener{
         .....
         noDataFoundTextView.isVisible = yourAdapter.itemCount == 0
         .....
}`

Hope it helps.
