### ISSUE TITLE
How can i get all datas？

### ISSUE THREAD

**Issue by David-Su** [googlecodelabs/android-paging#114]
For example,there are money shown on the recyclerview's each item and i want to calculate the total money,but i can not find the api which can get all the datas on the recyclerview .

**Comment by iamarjun** [comment]
@David-Su you must be passing some list to the recycler view's adapter which the recycler view then displays, so you can use that list which you pass to the adapter to get the sum of the money.

**Comment by David-Su** [comment]
> @David-Su you must be passing some list to the recycler view's adapter which the recycler view then displays, so you can use that list which you pass to the adapter to get the total sum of the money.

Thanks your answer,but you are talking about the common usage. I want to know the usage with paging3, all i got was PagingData, and there was no list.

**Comment by florina-muntenescu** [comment]
You shouldn't be getting the data from recyclerview. you should get this information in your data layer as the total money most likely doesn't depend only on those items displayed on the screen, but on all items.
