### ISSUE TITLE
No Bug but a Suggestion

### ISSUE THREAD

**Issue by sunday58** [googlecodelabs/android-paging#115]
At chapter 17. Request and save data - implementation.
After implementing page with TODO and initializing apiResponse. Page throws an error of type int. 
the error disappears after implementing the variables of  LoadType.REFRESH,  LoadType.PREPEND, LoadType.APPEND.
My suggestion is that a note should be added letting a beginner know that the page will throw an error, and the error will go away after implementing the loadtypes.

**Comment by tunjid** [comment]
@sunday58 I think this error is related to rate limiting by the Github api, not tho anything in the code lab. As The code lab uses Github's free unauthenticated api, your API address has a limit to how many requests it can make before it errors out. This will continue until the rate limit expires.
