### ISSUE TITLE
Can't Access paging 3 codelabs

### ISSUE THREAD

**Issue by aptx113** [googlecodelabs/android-paging#123]
As title, I encounter 404 after clicking the link to paging codelabs  everywhere, please fix these thx

**Comment by TedHopp** [comment]
Same here. I wonder if it is related to the recent alpha08 release of the paging 3 library.

**Comment by florina-muntenescu** [comment]
This shouldn't be the case anymore. 
Could you try it out: [codelab](https://developer.android.com/codelabs/android-paging#0) ?
