### ISSUE TITLE
Is it support looper recyclerview?

### ISSUE THREAD

**Issue by DorisGM** [googlecodelabs/android-paging#126]
I just want to use paging at looper verticalGridView. And I config placeholder to true. And obtain data from database. When i press keyup at index 0 item, i set the selection to adapter.size -1 to show the end of list. It seems like everything is ok when i from beginning to end. But when i press keydown at end of list make selection from end to 0. App is crash. i think it's maybe because of this "adapters that automatically request data as the user scrolls toward the end of the loaded data." 
 
btw,  can i dynamically override pagingSource's countItems? because of  i want to use placeholder when request data from network.

Thanks.
[PagingSample.zip](https://github.com/googlecodelabs/android-paging/files/5508634/PagingSample.zip)

**Comment by florina-muntenescu** [comment]
This issue is not related to the codelab
