### ISSUE TITLE
Importance of sorting sync between network API and DB query?

### ISSUE THREAD

**Issue by niekvse** [googlecodelabs/android-paging#127]
Ok, so this is more of a question: 

In the `GithubService`, the network query is done as follows:

```kotlin
/**
     * Get repos ordered by stars.
     */
    @GET("search/repositories?sort=stars")
    suspend fun searchRepos(
            @Query("q") query: String,
            @Query("page") page: Int,
            @Query("per_page") itemsPerPage: Int
    ): RepoSearchResponse
```

Then, in the `RepoDao`, the DB (Room) query is done as follows:

```kotlin
@Query("SELECT * FROM repos WHERE " +
   "name LIKE :queryString OR description LIKE :queryString " +
   "ORDER BY stars DESC, name ASC")
    fun reposByName(queryString: String): PagingSource<Int, Repo>
```

Obviously, it seems important that these two queries are "in sync", so that both of them end up with the exact same ordering of the Repo's, otherwise you may request a new page, but the API may return data that doesn't result in more data for the corresponding DB query. 

However, what I miss in the documentation is how important this is: it seems vitally important, but it's just sort of assumed that you understand this. But since the backend may use different internal rules for ordering (apparently it already has some hidden rule where it first orders by stars and then by name, which is not explicitly specified in the network query), it seems like it may not always match up 100%. If so, what's the resulting behavior of the Paging library? 

It would perhaps make more sense if the exact backend ordering was used to sort on in the local DB query, rather than relying on "luck". Could you change the codelab to include this information?

**Comment by tunjid** [comment]
@niekvse all things being equal, the sorting in the API should be 100% independent of the sorting in the the DB query. When the `RemoteMediator` is used, the results are not fed directly to the DB, instead they are persisted to disk. This causes the paging source to be invalidated, and another database query to be invoked. The DB is _always_ the source of truth.

**Comment by alammer** [comment]
One simple rule follows from your words - when you working with PageMediator, the storage and fetch data from Room should be organized BY DEVELOPER HIMSELF in such a way that receiving new data from remote API (by PREPEND/APPEND call) never changes the current dataset in PagingState, but creates a new one solely by adding data to its start/end. Considering that not everyone here are experienced developer, the lack of focusing on this condition also puzzled me. The existing documentation for codelab and most of the articles on resources like medium give newbie like me the false impression that all that is needed to work with the Paging library is just to get next page from remote API and save it to Room as it. As the previous speaker pointed out, this is not entirely correct.

**Comment by tunjid** [comment]
@alammer I'm not quite sure I follow. Are you saying that there should be a callout that Room queries should be sorted?

**Comment by alammer** [comment]
Sorry, for my english :) I think this guy will be able to convey to you the essence of my concern in a more accessible way :) 

https://www.bornfight.com/blog/android-paging-3-library-with-page-and-limit-parameters/

**Paging using item keys seems defaultish**
