### ISSUE TITLE
Not Bug, rather a question

### ISSUE THREAD

**Issue by abhinav272** [googlecodelabs/android-paging#13]
Room smartly runs all the queries which return `LiveData` or `Observable` on a background thread, then why when returning `DataSource.Factory` it runs on UI thread and we have to manually run it on a background thread?

**Comment by AdamSHurwitz** [comment]
@abhinav272, Threading is handled on the background by [`PagedList`][pagedList] with the extension function `toLiveData` for the Pagin 2 library.

> If you use LivePagedListBuilder to get a LiveData<PagedList>, it will initialize PagedLists on a background thread for you.

Then, if you log the thread the data is returned on in the ViewModel, it is returned on the main thread by the paging 2 library.

_SomeRepository.kt_
```Kotlin
fun initFeed() = flow {
        try {
            val tweetsQuery = dao.getAllTweets()
                .toLiveData(
                    pageSize = FEED_PAGEDLIST_SIZE,
                    boundaryCallback = boundaryCallBack
                ).asFlow()
            tweetsQuery.collect { results ->
                emit(success(results))
            }
        } catch (exception: Exception) {
            emit(error(exception.localizedMessage!!, null))
        }
    }
```

_SomeViewModel.kt_
```Kotlin
private fun initFeed() {
        repository.initFeed().onEach { results ->
            _viewEffect._isLoading.value = Event(false)
            _viewState._feed.value = results.data
        }.launchIn(viewModelScope)
}
```

[pagedList]: https://developer.android.com/reference/androidx/paging/PagedList
