### ISSUE TITLE
Pagination is calling unnecessary api

### ISSUE THREAD

**Issue by pom1004** [googlecodelabs/android-paging#131]
If you check the log in the first pagination it's again calling page 1 and then page 2 so incorrect data is getting reflected and also 2 API call is happening one is old page=1 and another is page=2. PFA.
![image](https://user-images.githubusercontent.com/8271730/100087665-10a17480-2e75-11eb-8314-26dc2cb1672b.png)

**Comment by shoanchikato** [comment]
Duplicate of #79

**Comment by florina-muntenescu** [comment]
Fixed with #143
