### ISSUE TITLE
searchRepo method referred to as search

### ISSUE THREAD

**Issue by MelerosPaw** [googlecodelabs/android-paging#133]
In [step 9](https://developer.android.com/codelabs/android-paging#8) code snippets display method as `search()`, but the codelab refers to that method as `searchRepo()` all the time. This happens for the first time in this sentence:

> The search function should be called in SearchRepositoriesActivity in the onCreate() method, In updateRepoListFromInput(), replace the viewModel and adapter calls with searchRepo:

First reference to this method is in [step 7](https://developer.android.com/codelabs/android-paging#6), referred both in the codelab and the snippet as `searchRepo()`.

**Comment by florina-muntenescu** [comment]
> In [step 9](https://developer.android.com/codelabs/android-paging#8) code snippets display method as `search()`, but the codelab refers to that method as `searchRepo()` all the time. This happens for the first time in this sentence:
> 
> > The search function should be called in SearchRepositoriesActivity in the onCreate() method, In updateRepoListFromInput(), replace the viewModel and adapter calls with searchRepo:
> 
Fixed this instance (codelab text not yet published).
Not sure where else this is happening. 

> First reference to this method is in [step 7](https://developer.android.com/codelabs/android-paging#6), referred both in the codelab and the snippet as `searchRepo()`.
In step7 `searchRepo` is correct - as it refers to the `SearchRepositoriesViewModel.searchRepo` method.
