### ISSUE TITLE
Inconsistent code for val property named `page`

### ISSUE THREAD

**Issue by shrishkukde** [googlecodelabs/android-paging#137]
**At Step 18 - Getting the page based on the LoadType.**

Inside **LoadType.PREPEND -> {} block** , the value of **endOfPaginationReached** is set to **true**.
However, at the end of the same page, below the line: **Now, the full page computation looks like this:**,
the value of above feild is set to false.

i.e. **endOfPaginationReached = false**

This two pieces of code contradict each other and creates confusion. Please correct.

Here are the images for quick references:
 
**IMAGE 1 [STEP 18]**

---
![image](https://user-images.githubusercontent.com/38505105/102679699-9cd65b80-41d7-11eb-9c9d-2d9063da7218.png)

**IMAGE 2  [STEP 18]**

---
![image](https://user-images.githubusercontent.com/38505105/102679718-c3949200-41d7-11eb-88e7-5551cc9d3d9c.png)

**Comment by shrishkukde** [comment]
Hello Team, any update here ?

**Comment by dlam** [comment]
Hi there - the image at the top is correct, I think this was just a copy error. Thanks for pointing this out and bumping the thread, sorry it took awhile to get to this :smiley:

**Comment by florina-muntenescu** [comment]
Thanks for reporting. updated
