### ISSUE TITLE
Slight Modification required in class ReposLoadStateViewHolder

### ISSUE THREAD

**Issue by shrishkukde** [googlecodelabs/android-paging#142]
There is a correction required in **Step 10 Displaying the loading state in a footer**, 

Inside `class ReposLoadStateViewHolder`, the function `bind()` needs to be revisited.

The line `binding.errorMsg.isVisible = loadState !is LoadState.Loading` should be updated to `binding.errorMsg.isVisible = loadState is LoadState.Error`

Here `errorMsg `view should only be enabled when the `LoadState` is `LoadState.Error`

Please revisit and correct accordingly

**Comment by florina-muntenescu** [comment]
Fixed! Thanks for reporting
