### ISSUE TITLE
Delete a code line

### ISSUE THREAD

**Issue by dlqkfzlr** [googlecodelabs/android-paging#144]
In final code of [9. Trigger Network Updates],
the highlighted code should be removed after following all instructions of this page.
But it still remains on the revised code
![image](https://user-images.githubusercontent.com/44568146/104152199-33d2b400-5422-11eb-8ca5-ebc171ac7c39.png)

**Comment by prohakker2000** [comment]
Same line still exists in the guide. Fix this.

**Comment by florina-muntenescu** [comment]
Fixed thanks!
