### ISSUE TITLE
prepend and append to queue behind refresh

### ISSUE THREAD

**Issue by bironader** [googlecodelabs/android-paging#155]
According to this  [commit](https://android.googlesource.com/platform/frameworks/support/+/e754df9ed34341e5aa71e26427244951089e854b%5E%21/paging/common/src/main/kotlin/androidx/paging/RemoteMediatorAccessor.kt?fbclid=IwAR1ED_0_f-1KFQy0TXCnmWvihBTh8SsTY4EaygzKM-90NhZ2i7J9jCvxE00) paging version **(3.0.0-beta01)** now load prepend and append after refresh which leads to **nulls** remotes key and according to this [lap](https://developer.android.com/codelabs/android-paging#17) will throw **Remote key and the prevKey should not be null** so how can we get the remote key based on PagingState in this case?

**Comment by florina-muntenescu** [comment]
Codelab changed meanwhile. thanks for reporting
