### ISSUE TITLE
Flickering issue on branch step13-19_network_and_database

### ISSUE THREAD

**Issue by ThanosFisherman** [googlecodelabs/android-paging#157]
When the app first launches there is a noticeable flickering issue on the recyclerview items probably related to a bug in `GithubRemoteMediator` logic. 

You can even see the progress spinner for a while.

https://user-images.githubusercontent.com/4888330/110322943-8abcca00-801c-11eb-9987-b767b9b24f5b.mp4

**Comment by florina-muntenescu** [comment]
Fixed by using `LoadState.mediator`
