### ISSUE TITLE
calling adapter.refresh() crashes with illegalstateException

### ISSUE THREAD

**Issue by raghunandankavi2010** [googlecodelabs/android-paging#164]
```
 java.lang.IllegalStateException: An instance of PagingSource was re-used when Pager expected to create a new
    instance. Ensure that the pagingSourceFactory passed to Pager always returns a
    new instance of PagingSource.
```

Crashed with above exception. Added only swipe refresh and called adapter.refresh()

**Comment by raghunandankavi2010** [comment]
Need to create a new paging source when you call refresh. It was a mistake at my end.

**Comment by uszkaisandor** [comment]
@raghunandankavi2010 
How could you create new paging source? 

Are you created a whole new Pager object? If not, how did you updated paging source in Pager?

**Comment by raghunandankavi2010** [comment]
This issue can b closed. Sorry this was a minor mistake at my end.
