### ISSUE TITLE
NETWORK_PAGE_SIZE not accessible

### ISSUE THREAD

**Issue by stevenshapiro** [googlecodelabs/android-paging#168]
In "Step 5: Define the source of data", NETWORK_PAGE_SIZE is not accessible in GithubPagingSource,kt, since it is declared private in GithubRepository.kt.  It is still declared private in "Step 6: Build and configure PagingData".

**Comment by tunjid** [comment]
@stevenshapiro this is fixed now, thank you. The project was rebased, so you may need to delete your local branch and pull it again.
