### ISSUE TITLE
Typo in 18. Getting the page based on the LoadType

### ISSUE THREAD

**Issue by AlexPopov487** [googlecodelabs/android-paging#174]
There is a typo in the second paragraph of "LoadType.APPEND" :

"If remoteKeys is null, that means the refresh result is not in the database yet. We can return Success with endOfPaginationReached = false because Paging will call this method again if RemoteKeys becomes non-null. If remoteKeys is not null but its **_prevKey_** is null, that means we've reached the end of pagination for append."

There must have been **nextKey** instead of a **prevKey**. The same typo is duplicated in the comments in the code snippet right below the first typo

**Comment by tunjid** [comment]
Hi! Thanks for bringing this up, I'm currently in the process of fixing it.

**Comment by AlexPopov487** [comment]
Happy to help:)

чт, 17 июн. 2021 г., 13:53 Adetunji Dahunsi ***@***.***>:

**Comment by tunjid** [comment]
@AlexPopov487 this should be fixe now, thanks again for pointing it out.
