### ISSUE TITLE
Link navigates to 404

### ISSUE THREAD

**Issue by cory-austin** [googlecodelabs/android-paging#183]
The link at the end of the lesson goes to a page which does not exist.

Advanced Coroutines with Kotlin Flow and LiveData codelab:
https://codelabs.developers.google.com/codelabs/advanced-kotlin-coroutines

**Comment by tunjid** [comment]
@cory-austin sorry about that, it looks like the root has changed, but the url fragment is the same.

Please refer to https://developer.android.com/codelabs/advanced-kotlin-coroutines#0

For what you need, I'll update the doc soon.

**Comment by tunjid** [comment]
@cory-austin please can you point me to where in the codelab you found this dead link? I can't find it anywhere.

**Comment by cory-austin** [comment]
The last line of step 1.  The one that says "Advanced Coroutines with Kotlin Flow and LiveData codelab."

**Comment by tunjid** [comment]
It should be updated shortly.
