### ISSUE TITLE
A screen flashes when you refresh the page

### ISSUE THREAD

**Issue by lifuyuan123** [googlecodelabs/android-paging#191]
Add SwipeRefreshLayout, and run Adapter :: Refresh in the drop-down list. The page flashes

**Comment by tunjid** [comment]
@lifuyuan123 As `Adapter :: Refresh` causes a new `PagingData` to be created, this is to be expected. Please file a bug on the [Paging Buganizer](https://b.corp.google.com/issues?q=status:open%20componentid:413106) detailing the preferred behavior. cc @dlam
