### ISSUE TITLE
adapter.refresh() not working in RxPagingSource 

### ISSUE THREAD

**Issue by vijay81** [googlecodelabs/android-paging#192]
When i'm calling adapter.refresh() in **RxPagingSource** in Paging3 (3.0.1 latest) than page not refresh

**Comment by tunjid** [comment]
@vijay81 please file a bug on the [Paging bug tracker](https://b.corp.google.com/issues?q=status:open%20componentid:413106) with steps, and if possible code, on how to reproduce.
