### ISSUE TITLE
Different code between codelabs and github

### ISSUE THREAD

**Issue by ichvandi** [googlecodelabs/android-paging#194]
Data is not fetched at the first time because in the codelabs code, at `searches` variable, 
it is not calling method `.onStart { ... }`, but in github actually we need to call it.

|Codelabs (page 7)|Github|
|---|---|
|![Codelabs Image](https://user-images.githubusercontent.com/23291739/129905687-134c557f-813a-4049-9701-9f71ec1bacc9.png)|![Github Image](https://user-images.githubusercontent.com/23291739/129905739-ed8672c5-fab4-45c4-acad-96a0a72346ba.png)|

`Codelabs`
```kt
val searches = actionStateFlow
            .filterIsInstance<UiAction.Search>()
            .distinctUntilChanged()
```

`Github`
```kt
val searches = actionStateFlow
            .filterIsInstance<UiAction.Search>()
            .distinctUntilChanged()
            .onStart { emit(UiAction.Search(query = initialQuery)) }
```

also in codelabs (page 9) said `We can now remove binding.list.scrollToPosition(0) from updateRepoListFromInput().`, but in codelabs and github the code isn't removed
![image](https://user-images.githubusercontent.com/23291739/129908580-00f38ebc-14d6-4f3a-a5e4-ab0ffea118de.png)

**Comment by tunjid** [comment]
Oh wow, thanks for catching this! I'll fix it as soon as I'm able to.

**Comment by tunjid** [comment]
Fixed.
