### ISSUE TITLE
The Codelab code for 'SearchRepositoriesViewModel.searchRepo' is not the Same as GitHub Code

### ISSUE THREAD

**Issue by joec58** [googlecodelabs/android-paging#197]
In task 12 "Adding List Separators", for method `SearchRepositoriesViewModel.searchRepo` we are given code has undeclared variables:

```kotlin
val lastResult = currentSearchResult
if (queryString == currentQueryValue && lastResult != null) {
    return lastResult
 }
currentQueryValue = queryString
```

at the being of of the method and

```kotlin
currentSearchResult = newResult
return newResult
```
at the end.

These lines are not in the GitHub code for this exercise.

**Comment by tunjid** [comment]
Fixed.
