### ISSUE TITLE
Step 19, Codelab Function not in Github Code

### ISSUE THREAD

**Issue by joec58** [googlecodelabs/android-paging#198]
The last part of Step 19, "Update the paging Flow creation", refers to a `SearchRepositoriesActivity.initAdapter` function that exists nowhere in the prior steps nor in the Github code for this exercise.

It appears that the significant parts of this codelab `initAdapter` function  are changes merged into the coroutine at the end of `SearchRepositoriesActivity.ActivitySearchRepositoriesBinding.bindList`

**Comment by tunjid** [comment]
Thanks again for reporting this @joec58! Fixing.

**Comment by tunjid** [comment]
Fixed.
