### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by dfavaro** [googlecodelabs/android-paging#201]
https://github.com/googlecodelabs/android-paging/blob/a2042197c417037adf1133f77ca20bc7b0b9ac8d/app/src/main/java/com/example/android/codelabs/paging/data/GithubRemoteMediator.kt#L78

could be:
`return nextKey ?: MediatorResult.Success(endOfPaginationReached = remoteKeys != null)`

or am I wrong?

**Comment by dlam** [comment]
That would return out of `RemoteMediator.load` method earliy with the wrong type.

Instead what we want is to retrieve the key to use for the actual remote load logic, but if we can't, then we simply exit the function early with `MediatorResult.Success(..)`
