### ISSUE TITLE
Our app finally compiles! on Page 8

### ISSUE THREAD

**Issue by ataulm** [googlecodelabs/android-paging#21]
The app can be compiled and run at the end of Page 7, without swapping the ListAdapter for a PagedListAdapter (since PagedList is a List, which ListAdapter accepts).

Suggest:

- remove "Our app finally compiles!" on Page 8, or moving it before the instruction to change to PagedListAdapter.
- Add note on what the PagedListAdapter provides over a ListAdapter; i.e. is there _any_ benefit (or detrimental) to the work up to this point if we didn't swap the ListAdapter for PagedListAdapter?

**Comment by florina-muntenescu** [comment]
Codelab text changed meanwhile. Feel free to create a new issue or reopen this one if the issue still exists.
