### ISSUE TITLE
there is no real example for PositionalDataSource 

### ISSUE THREAD

**Issue by s-kh** [googlecodelabs/android-paging#22]
i can't find example for Positional Data Source :(

**Comment by ferozkhandev** [comment]
I also want an example for Positional Data Source in Java. Have you found a solution @s-kh ?

**Comment by s-kh** [comment]
@ferozkhandev no i couldn't found anything:/

**Comment by ferozkhandev** [comment]
Then I think this would be helpful for you as I got succeed at some extent.
https://stackoverflow.com/questions/55335251/loadinitial-method-not-getting-called-in-positionaldatasourceitem

**Comment by sepidevatankhah** [comment]
I also want an example for Positional Data Source in Kotlin. Have you found a solution @s-kh ?

**Comment by s-kh** [comment]
Unfortunately no

**Comment by AomiDIU** [comment]
https://guides.codepath.com/android/Building-Data-driven-Apps-with-Parse#using-with-android-paging-library

**Comment by vberezkin** [comment]
Here is another example of PositionalDataSource https://github.com/vberezkin/giphy

**Comment by florina-muntenescu** [comment]
Not part of this sample
