### ISSUE TITLE
Question about Architecture

### ISSUE THREAD

**Issue by ignaciogs** [googlecodelabs/android-paging#24]
Hi @florina-muntenescu, I have a question 

In the class SearchRepositoriesViewModel.kt you are using the Transformations.map(). This method use a MediatorLiveData and this a observerForever. I have read in the android documentation that a viewmodel doesn't should observe never a liveData object. I attached a capture. My question is ¿It's good pratice use the MediatorLiveData or Transformations into ViewModel class?

![image](https://user-images.githubusercontent.com/708659/53163233-eb137700-35cd-11e9-8084-8e757bf996c8.png)

Thank you very much and forgive the inconvenience.

**Comment by florina-muntenescu** [comment]
Yes. You can use `MediatorLiveData` and `Transformation`s in a `ViewModel`
