### ISSUE TITLE
Does not work with Android Studio 3.5 stable. Asks for Studio 4.0 or newer.

### ISSUE THREAD

**Issue by rajBopche** [googlecodelabs/android-paging#36]
I cloned this project and while building, the build finished with **This version of Android Studio cannot open this project, please retry with Android Studio 4.0 or newer**.

Android Studio: 3.5.2
GradleWrapper: distributionUrl=https\://services.gradle.org/distributions/gradle-6.1-rc-1-all.zip

<img width="1184" alt="Screen Shot 2020-02-04 at 3 12 44 PM" src="https://user-images.githubusercontent.com/42612104/73732796-ceca0500-4760-11ea-9bf5-1d5fd7e5f7dc.png">

**Comment by augustgrun** [comment]
In build.gradle (Project) modify dependencies to use your preferred version of Android Studio.

`classpath 'com.android.tools.build:gradle:3.5.3`

**Comment by rajBopche** [comment]
> In build.gradle (Project) modify dependencies to use your preferred version of Android Studio.
> 
> `classpath 'com.android.tools.build:gradle:3.5.3`

Yea, it was the real issue. The classpath was not matching the desired version. Thanx, a lot mate.

**Comment by AdoniasAlcantara** [comment]
Why isn't stable version of Android Studio the default?
