### ISSUE TITLE
Android Studio 4.0 is required to run this codelab now...

### ISSUE THREAD

**Issue by Bradleycorn** [googlecodelabs/android-paging#38]
PR #33 (Bumping Versions) updates the project to use android gradle plugin version `4.0.0-alpha9` . As a result, this project will only open on Android Studio version 4.0 and greater. However, the Codelab Intro pages says you only need Android Studio 3.4 or later.

**Comment by prudhvir3ddy** [comment]
@Bradleycorn you got plans to open a PR?

**Comment by Bradleycorn** [comment]
@prudhvir3ddy nope. I don't know Google's intensions here. Should the project in this repo be reverted back to support AS Studio 3.4 to match the stated requirements in the code lab, or should the code lab be updated to state that AS 4.0 is required...

**Comment by kshailes** [comment]
so how to open it? Is it a joke?

**Comment by taniacse** [comment]
Is There any solution for it................ its not really expected from google........... too much annoying

**Comment by prudhvir3ddy** [comment]
@kshailes @taniacse just google it you need to downgrade version of Gradle plugin.

**Comment by yuhushuan** [comment]
root build.gradle
```
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }
}
```

**Comment by darwinyip** [comment]
Android studio 4.0 is still in beta. Why would a codelab  require that?
