### ISSUE TITLE
Missing ReposAdapter Class!

### ISSUE THREAD

**Issue by pngen** [googlecodelabs/android-paging#4]
On Step 8 of the Android Paging codelab, the class file for ReposAdapter is missing. Step 8 says to modify the ReposAdapter from a ListAdapter to a PagedListAdapter, but the class file ReposAdapter itself is missing entirely.

**Comment by florina-muntenescu** [comment]
The file is [here](https://github.com/googlecodelabs/android-paging/blob/master/app/src/main/java/com/example/android/codelabs/paging/ui/ReposAdapter.kt).
