### ISSUE TITLE
Terminology error in step 9

### ISSUE THREAD

**Issue by zsmb13** [googlecodelabs/android-paging#5]
Step 9 of the code lab includes the following:

> Create a backing field for it, and change the type of `networkErrors` to `LiveData<String>`.

The property already has a backing *field*, what we're doing here is creating a [backing *property*](https://kotlinlang.org/docs/reference/properties.html#backing-properties).

Later down the page, this comes up again:

>Update the `requestAndSaveData()` method to use the backing field `_networkErrors`.

**Comment by florina-muntenescu** [comment]
Thanks! Codelab text updated.
