### ISSUE TITLE
List divider at start of list

### ISSUE THREAD

**Issue by fedorenkoalex** [googlecodelabs/android-paging#58]
When use Pager with `remoteMediator`, object "before" in `insertSeparators` function always not null. So there is on possible to insert divider at first place.

**Comment by alvindizon** [comment]
Yep it's possible. See [this](https://github.com/Marchuck/Paging3/blob/ba56fcb7650f4b7c9d33d6dae5b1a7593534900b/app/src/main/java/pl/marczak/paging3/PokedexStreamProvider.kt) for an example

**Comment by tunjid** [comment]
@fedorenkoalex much like alvindizon said, using the null check to insert the separator is the way to go.

```kotlin
        insertSeparators(it) { before: MyItem?, after: MyItem? ->
            if (before == null) {
                return@insertSeparators MyHeaderItem()
            }
            ...
        }
```
