### ISSUE TITLE
Application get crashed when reached at end.

### ISSUE THREAD

**Issue by milanvthakor** [googlecodelabs/android-paging#59]
I have followed codelabs paging 3 tutorial. I have implemented paging from network and database. 

Inside GithubRemoteMediator.kt
I have set val endOfPaginationReached = page > 2 to allow maximum 2 pages for testing. 
So, the problem is when I reach at the last page of list, application get crashed as remoteKeys.nextKey is null(as we have set nextKey=null for last page of list). 

Also how to support caching when application is open without internet connection. currently it is showing retry button. How to show previously loaded data. I have tried to fix this by removing
// clear all tables in the database
            if (loadType == LoadType.REFRESH) {
                repoDatabase.remoteKeysDao().clearRemoteKeys()
                repoDatabase.reposDao().clearRepos()
            }
as this will now not gone delete data from database.
But still Pager does not load data available.

So how I can fix this problem?
Is there any way of detecting end of paging?
Why Pager is not returning data available in database.

**Comment by myolwin00** [comment]
I have the same issue that there's no data(from database) when I open the app without internet connection.

**Comment by florina-muntenescu** [comment]
Paging was returning data available in the database.
We had a bug in the code that decides what to display: the list or an error. 
Fixed meanwhile.
