### ISSUE TITLE
Why sample is in Kotlin language?

### ISSUE THREAD

**Issue by sephuxeresh** [googlecodelabs/android-paging#6]
Really? Why project is in Kotlin language? Please, give us the choice between pure Java and Kotlin. 

P.S. I came from https://codelabs.developers.google.com/codelabs/android-paging/index.html

**Comment by mustafiz012** [comment]
Are you trying to divert developers to Kotlin forcibly?? :-1: You can do Kotin alongside Java.

**Comment by kaushiknsanji** [comment]
Java Developers can refer this [sample](https://github.com/kaushiknsanji/PagingSampleCodelab). It also contains references for Android paging implementations done in java.

**Comment by Dilip23** [comment]
Kotlin makes Development more easier and removes lot of boiler-plate code .
So Developers can concentrate on building core of their app . It is definitely a great step to move towards Kotlin

**Comment by mustafiz012** [comment]
@Dilip23 You're right in a way! But, when you're working for a company, you would not have that much time to learn Kotlin alongside project work (which is in Java). Hope we're gonna grab Kotlin ASAP.
