### ISSUE TITLE
App crashes with offline mode on Android API 29, Android Studio 4.2 canary 1 

### ISSUE THREAD

**Issue by mr3y-the-programmer** [googlecodelabs/android-paging#66]
at the end of codelab we finished implementing GithubRemoteMediator, but when running the app it crashes, saying in logcat "Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number." , However, RepoDatabase file is:
```
@Database(
        entities = [Repo::class, RemoteKeys::class],
        version = 1,
        exportSchema = false
)
abstract class RepoDatabase : RoomDatabase() {  
```

As you can see, I didn't increase the version or manipulate any other related database files I just walked through codelab but can't figure out why this error happens?

**Comment by AbdoNasr3** [comment]
Also, this issue #60 mentions that Offline cache is broken, So I'm not the only one who face this problem

**Comment by vignesh6** [comment]
Update the version no and Add migration to the Room Database. when ever you create or alter table.

**Comment by florina-muntenescu** [comment]
If you ran and installed the application after adding the Repo entity, adding the RemoteKeys entity changes the database schema. This means that you will have to increase the database version to 2 and when building your database, before calling build(), call .fallbackToDestructiveMigration().

Adding a note in the codelab
