### ISSUE TITLE
App not working in offline mode

### ISSUE THREAD

**Issue by vignesh6** [googlecodelabs/android-paging#68]
The latest Repo with RemoteMediator implemented does not provide offline support it shows Retry button in offline.

**Comment by samiazar** [comment]
I have the same issue, do you find any workaround?

**Comment by rabyunghwa** [comment]
The library is still in alpha. Hopefully they'll come up with a fix soon.

**Comment by isamotiuc** [comment]
It works with ALPHA-2, just remove from `SearchRepositoriesActivity` this logic, that hides listview in offline mode.
```
binding.list.isVisible = loadState.refresh is LoadState.NotLoading
```

**Comment by florina-muntenescu** [comment]
Fixed meanwhile
