### ISSUE TITLE
The code presented at the end of 9th step doesnt match the code in solution branch https://github.com/googlecodelabs/android-paging/tree/step5-9_paging_3.0

### ISSUE THREAD

**Issue by kriticalflare** [googlecodelabs/android-paging#69]
The code in the function `initSearch` shown at the end of step 9 doesn't match the instructions given nor the actual code in the solution branch https://github.com/googlecodelabs/android-paging/blob/step5-9_paging_3.0/app/src/main/java/com/example/android/codelabs/paging/ui/SearchRepositoriesActivity.kt#L104

<img src="https://user-images.githubusercontent.com/42350771/85926112-b6e35100-b8ba-11ea-97f5-b31af045a874.png" />

**Comment by florina-muntenescu** [comment]
Good catch! Thanks for reporting this.
Codelab text fixed
