### ISSUE TITLE
Multiple Network requests issued

### ISSUE THREAD

**Issue by kaushiknsanji** [googlecodelabs/android-paging#7]
* Lets say user is viewing the repositories for the search "Android", and the scrolled to about 200 items in the result. 
* In other words, 200 items are now loaded into the RecyclerView's Adapter. The Last Page index at this stage will be 4 (for 50 items requested per page from the network - `NETWORK_PAGE_SIZE`) and Page 5 is awaiting to be retrieved. 
* The User now rotates the device to Landscape orientation.
* Now the user scrolls to the end. At this stage, network request will be triggered but it will start requesting from page 1, until the page to be shown is requested. In the stated example, it will poll from page index 1 to page index 5, instead of just the page index 5.

This also happens when the user kills the app and relaunches the app to view the query results for a previously searched query. This applies for both the code samples (with or without the paging library).

Is this intended to work like this or is this a bug?

**Comment by florina-muntenescu** [comment]
Codelab changed meanwhile. Feel free to create a new issue or reopen this one if the issue still exists.
