### ISSUE TITLE
Code completey different from android codelab tutorial 

### ISSUE THREAD

**Issue by gharShaddi** [googlecodelabs/android-paging#71]
there is using of list adapter and no paging 3.0 resoures uses any where in code 
the tutorial guide to create GitPagingSource useing PagingSource 
and then GitPagingData then GitRepository included with RepoSearchResponse and then guide to buid ReloadAdapter with view holder and required setup to init adapter and viewmodel data flow oberser but here nothing match the code no {
RemoteMediatorSource or dao or room where used 
}

thats makes tutorial uncomplete

**Comment by isamotiuc** [comment]
This project contains different git branches. If you want to check `RemoteMediatorSource` implementation, change to [step13-19_network_and_database](https://github.com/googlecodelabs/android-paging/tree/step13-19_network_and_database) branch
