### ISSUE TITLE
Wrong method name in Step 9

### ISSUE THREAD

**Issue by gabrielsallesrg** [googlecodelabs/android-paging#73]
In the description, says to change some code in the method `updateRepoListFromInputupdateRepoListFromInput()`, but the right name is `updateRepoListFromInput()`

**Comment by florina-muntenescu** [comment]
Codelab updated.
Thanks for reporting this!

**Comment by jorgecasariego** [comment]
Hi, I want to add something related to the step 9. In the description says to update **initSearch** method and at every new emission of the flow, let's scroll to position 0 adding this code:

![image](https://user-images.githubusercontent.com/2581647/91896142-5da2ef80-ec66-11ea-9324-91b16193fb3b.png)

But at the end, in the Activity with the complete code shows this:

![image](https://user-images.githubusercontent.com/2581647/91896252-862ae980-ec66-11ea-986f-f200288af56f.png)
