### ISSUE TITLE
IN_QUALIFIER ??

### ISSUE THREAD

**Issue by dombroks** [googlecodelabs/android-paging#75]
what IN_QUALIFIER means in the code ? what it does ?

**Comment by yoobi** [comment]
It is just for the github API, 
When you do : https://api.github.com/search/repositories?sort=stars&q=Android and https://api.github.com/search/repositories?sort=stars&q=Androidin:name,description you don't have the same result, I'm guessing that "in:name,description" is to search the term only in name and description

**Comment by florina-muntenescu** [comment]
[`IN`](https://www.sqlitetutorial.net/sqlite-in/) is an "operator to determine whether a value matches any value in a list of values or a result of a subquery"
