### ISSUE TITLE
load more bug

### ISSUE THREAD

**Issue by laibinzhi** [googlecodelabs/android-paging#77]
Every time I pull down to load more, after the network data request is successful, the list locates the first piece of data

**Comment by siddhantkumar20** [comment]
this bug and crashing bug is cause by 
`lifecycleScope.launch {
            @OptIn(ExperimentalPagingApi::class)
            adapter.dataRefreshFlow.collect {
                binding.list.scrollToPosition(0)
            }
        }
`
I removed this code and everything seems work fine, IDK BUT....
I guess dataRefreshFlow is getting called when data is appended or prepended , causing recyclerview to scroll to top, which causes recyclerview to throw exception in the second case when this happens.
I also tried to update to latest release of pagination and recyclerview libs but same thing,
For now this thing works well..

**Comment by florina-muntenescu** [comment]
The codelab doesn't implement "pull to refresh". What do you mean with "pull down to load more"?

**Comment by siddhantkumar20** [comment]
> The codelab doesn't implement "pull to refresh". What do you mean with "pull down to load more"?

I think he means, when scrolling down the list, actually same thing i.e. the list scrolls to top when ever load type is APPEND in RemoteMediator's load function, happens in https://github.com/android/architecture-components-samples/tree/master/PagingWithNetworkSample too when using db+network. I guess there's a bug with datarefreshflow when using with remotemediator, it is even emitted when load type is append.
P.S.: Sorry if something is wrong with my explanation I am a beginner and this is what I observed...

**Comment by RoarGronmo** [comment]
I was plagued by a "channel was closed" error, and was advised to use `collectLatest` instead of `collect` on the Flow expressions. But there are still issues according to subsequent/simultanius load APPEND issues, when calling suspended (room) functions inside load.

Please take a look here: https://issuetracker.google.com/issues/160192222

RG

**Comment by florina-muntenescu** [comment]
This was fixed meanwhile. make sure you force pull as the changes are rebased
