### ISSUE TITLE
Where I can find the old way of using the Paging Library ?

### ISSUE THREAD

**Issue by CelikAbdullah** [googlecodelabs/android-paging#78]
Hello, 

it's fine that you have now a Paging Library 3.0 with all the Flow stuff and other new things and so on. But I made my app using the old Paging Library with a BoundaryCallback and I am very happy with that.

I know that the software will always change but at this point, I do not want to integrate Flow into my app because it is an ExperimentalAPI which might be change in the future. 

Therefore, I searched for the codelab and the Paging github page which contained the old Paging Library with PagedList.BoundaryCallback and so on. 

Can you also upload that old project, please ?

**Comment by florina-muntenescu** [comment]
I pushed the [Paging 2 solution branch](https://github.com/googlecodelabs/android-paging/tree/paging2_solution).
Hope it helps

**Comment by CelikAbdullah** [comment]
Thank you :) But after seeing the Header & Footer stuff + the Separator item feature, I was convinced to integrate Paging 3 library into my app. 
Nevertheless, thank you for your effort.

**Comment by jakubosiak** [comment]
I keep getting these emails even though I unsubscribed from this thread a
couple of times, can you fix it?
