### ISSUE TITLE
initialLoadSize issue

### ISSUE THREAD

**Issue by IsLery** [googlecodelabs/android-paging#79]
Please provide to the codelab some information about initialLoadSize of Pager class (in section 6).
It may be confusing for beginners who try making applications based on this codelab, For example, when we load data in small portions, less than default initialLoadSize, same data can be loaded multiple times (it took me some time to figure out, that that was the reason and I'm probably not the only one).

**Comment by doilio** [comment]
I've been having an issue with something like this.
I seem to be getting stuck on LoadType.PREPEND.

I've put Logs inside the functions that give back the position based on the loadType.
![errr](https://user-images.githubusercontent.com/38020305/88545411-4182b180-d01b-11ea-94d1-f14b3582c7c7.PNG)



For this codelab I get:
```
codelabs.paging D/KEYS: REFRESH-> null -> null 
codelabs.paging D/KEYS: APPEND-> null -> 2 
codelabs.paging D/KEYS: APPEND-> 1 -> 3 
codelabs.paging D/KEYS: APPEND-> 2 -> 4 
```

On my code I get:

```
RemoteMediator: REFRESH-> null -> null 
RemoteMediator: APPEND-> null -> 2 
RemoteMediator: PREPEND-> 1 -> 3 
RemoteMediator: PREPEND-> 1 -> 3 
RemoteMediator: PREPEND-> 1 -> 3 
RemoteMediator: PREPEND-> 1 -> 3 
RemoteMediator: PREPEND-> 1 -> 3 
RemoteMediator: PREPEND-> 1 -> 3 
RemoteMediator: PREPEND-> 1 -> 3 
RemoteMediator: PREPEND-> 1 -> 3 
RemoteMediator: PREPEND-> 1 -> 3 
```
And it doesn't stop. 
Have you faced something like this when implementing RemoteMediator on your project?

**Comment by SerggioC** [comment]
Why is this issue still open? 
Why is google launching codelabs with experimental features and alpha versions? 
This was supposed to be a final product ready to use!!!
