### ISSUE TITLE
List scrolls to random position after screen rotation

### ISSUE THREAD

**Issue by jakubosiak** [googlecodelabs/android-paging#8]
When I rotate screen at the beginning of the list everything works fine, list scrolls to the right position - there where it was before rotation. When I scroll a little bit further and pass position 60~ and rotate, it always scrolls up to position 59-60. When I scroll a lot further and rotate it doesn't scroll to position 59-60 nor to last position, but to position 0.

I have the same issue in my own app which I am creating according to this codelab, when I scroll past position 144~ and rotate the screen it always scrolls up to position 143-144. and if I scroll to position before 150 and rotate the screen list scrolls to correct position. When I scroll to position like 230~ and rotate it doesn't scroll to position 143-144 nor to last position, but to position 0.

**Comment by jakubosiak** [comment]
Alright, I think this happens because everytime fragment is recreated we make `viewModel.searchRepo(query)` call thus new RepoSearchResult is created. To avoid that situation we have to call `viewModel.searchRepo(query)` once in a fragment lifecycle.

**Comment by florina-muntenescu** [comment]
Codelab changed meanwhile. Feel free to create a new issue or reopen this one if the issue still exists.
