### ISSUE TITLE
Split this tutorial in with and without Room.

### ISSUE THREAD

**Issue by RoarGronmo** [googlecodelabs/android-paging#82]
You should split this codelab in two separate codelabs, where the first is w/o Room and the second with Room. As it is now, (new) users may get confused when the two solutions are in one codelab session.

RG

**Comment by florina-muntenescu** [comment]
Thanks for the suggestion. Given that the UI layer implementation would be the same, having another codelab would lead to partially duplicated content and double the maintenance cost.
