### ISSUE TITLE
Examples with Room: LiveData, Flow and RxJava (Observable, Flowable)

### ISSUE THREAD

**Issue by RoarGronmo** [googlecodelabs/android-paging#86]
Theese are 3 (maybe four) different ways of implementing the 'flowness' of data in a pager scenario. Could you please split this codelab in 3 (4) different ways of implementing the paging and tell us the benefits drawback with each of them.

**Comment by florina-muntenescu** [comment]
Our [docs](https://developer.android.com/topic/libraries/architecture/paging/v3-paged-data?hl=en) contain examples of how to use RxJava and Guava/LiveData.
Adding all of this to the codelab would massively increase the codelab code and text maintenance burden.
