### ISSUE TITLE
Scrolling sends me to the beginning

### ISSUE THREAD

**Issue by 2000Vlad** [googlecodelabs/android-paging#88]
I have downloaded the solution code from branch step13-19_network_and_database and every time a new page is loaded I am being scrolled back to the beginning

**Comment by florina-muntenescu** [comment]
Fixed meanwhile please force pull

**Comment by 2000Vlad** [comment]
The new code is working, however, I compared the new code to the old one and it looks to me virtually the same. Would you mind if I ask you what/where was the bug coming from?
