### ISSUE TITLE
UiUtils.kt is not found

### ISSUE THREAD

**Issue by STAR-ZERO** [googlecodelabs/android-paging#90]
https://developer.android.com/codelabs/android-paging#9

in Section 10

> To set the visibility, we're using the toVisibility() method defined in **UiUtils.kt**.

But I can't find the **UiUtils.kt**.

**Comment by florina-muntenescu** [comment]
Thanks! Sentence removed, as UiUtils.kt was removed in favor is [`isVisible`](https://developer.android.com/reference/kotlin/androidx/core/view/package-summary#isvisible)

**Comment by tachyonlabs** [comment]
I'm still seeing it in both the instructions and the code on https://developer.android.com/codelabs/android-paging#9

**Comment by roboirc** [comment]
What do we use to replace this statement? How do I use isVisible ?

**Comment by ch22843** [comment]
Same issue.  How do I use isVisible ?

**Comment by iamarjun** [comment]
> I'm still seeing it in both the instructions and the code on https://developer.android.com/codelabs/android-paging#9
> 
> And the initAdapter() code on https://developer.android.com/codelabs/android-paging#10 is using toVisibility also.


> What do we use to replace this statement? How do I use isVisible ?


> Same issue. How do I use isVisible ?
> Like this?:
> 
> ```
> binding.progressBar.isVisible = loadState is LoadState.Loading
> binding.retryButton.isVisible = loadState !is LoadState.Loading
> binding.errorMsg.isVisible = loadState !is LoadState.Loading
> ```

this extension is available in androidx.core:core-ktx dependency, just add/update to androidx.core:core-ktx:1.3.2 and access isVisible on any view, this is kotlin specific
