### ISSUE TITLE
Code in intermediate step does not match expected final code in Step 9

### ISSUE THREAD

**Issue by alvindizon** [googlecodelabs/android-paging#98]
In Step 9, we are asked to complete the ```initSearch``` with the following lines of code:

```
        // Scroll to top when the list is refreshed from network.
        lifecycleScope.launch {
            adapter.loadStateFlow
                   // Only emit when REFRESH LoadState changes.
                   .distinctUntilChangedBy { it.refresh }
                   // Only react to cases where REFRESH completes i.e., NotLoading.
                   .filter { it.refresh is LoadState.NotLoading }
                   .collect { binding.list.scrollToPosition(0) }
        }
```

However, at the end of the Step 9, the finished code for ```initSearch``` uses the following:

```
        lifecycleScope.launch {
            @OptIn(ExperimentalPagingApi::class)
            adapter.dataRefreshFlow.collect {
                binding.list.scrollToPosition(0)
            }
        }
```

Did I miss anything during the course of doing Step 9? Or is something really missing? I guess the final code is functionally the same with the intermediate code, but it's a little bit puzzling for me.

**Comment by sarjshah** [comment]
Also this line was removed whilst making the changes:
                binding.list.scrollToPosition(0):

from the below code which is supposed to be what the activity looks like after the changes


    private fun updateRepoListFromInput() {
        binding.searchRepo.text.trim().let {
            if (it.isNotEmpty()) {
                **binding.list.scrollToPosition(0)**
                search(it.toString())
            }
        }
    }

**Comment by florina-muntenescu** [comment]
Thank you for reporting. Fixed
